### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by wimmol** [wimmol/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by PavelZaitsev00** [comment]
people call me "the one of most discussed and global issue of our time"
it’s easy to get me and it's difficult to diagnose it
My hobby is walking in crowded and cool places in my spare time
I realy love to be in people, but they unfortunately are afraid of me

**Comment by PavelZaitsev00** [comment]
<h2>Résumé</h2>
                  <p>&mdash; People call me «one of the most discussed and global issue of our time».
                  It’s easy to get me and it's difficult to diagnose it.
                  My hobby is walking in crowded and cool places in my spare time.
                    I really love to be in people, but, unfortunately, they are afraid of me.</p>
