### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by wimmol** [wimmol/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by PavelZaitsev00** [comment]
likes
+5C˚, unwashed hands, weak immunity, crowding

fears
soap, ventilation, quarantine, medical masks, conscious citizens

symptoms
Cough, Shortness of breath or difficulty breathing, Fever, Chills, Repeated shaking with chills,  Muscle pain, Headache, Sore throat,  New loss of taste or smell

Complications
Acute Respiratory Failure, Pneumonia, Acute Respiratory Distress Syndrome (ARDS), Acute Liver Injury, Acute Cardiac Injury, Secondary Infection, Acute Kidney Injury, Septic Shock, Disseminated Intravascular Coagulation, Blood Clots

teachers
bird flu, swine influenza, spanish flu

**Comment by PavelZaitsev00** [comment]
<section>
                <h3>likes 😁</h3>
                <p class="tags small">+5C˚, unwashed hands, weak immunity, crowding</p>
              </section>
              <section>
                <h3>fears 😣</h3>
                <p class="tags small">soap, ventilation, quarantine, medical masks😷, conscious citizens</p>
              </section>
              <section>
                <h3>symptoms 😰</h3>
                <p class="tags small">Cough, Shortness of breath or difficulty breathing, Fever, Chills, Repeated shaking with chills,  Muscle pain, Headache, Sore throat,  New loss of taste or smell</p>
              </section>
              <section>
                <h3>Complications 🗣</h3>
                <p class="tags small">Acute Respiratory Failure, Pneumonia, Acute Respiratory Distress Syndrome (ARDS), Acute Liver Injury, Acute Cardiac Injury, Secondary Infection, Acute Kidney Injury, Septic Shock, Disseminated Intravascular Coagulation, Blood Clots</p>
              </section>
              <section>
                <h3>teachers 👨‍🏫</h3>
                <p class="tags small">bird flu, swine influenza, spanish flu</p>
              </section>
