### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by wimmol** [wimmol/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by PavelZaitsev00** [comment]
<h3>Main News</h3>
              <ul class="timeline">
                <li>
                  <p><em>31<sup>th</sup>Dec 2019</em></p>
                  <p>Wuhan Municipal Health Commission, China, reported a cluster of cases of pneumonia in Wuhan, Hubei Province. A novel coronavirus was eventually identified.</p>
                </li>
                <li>
                  <p><em>1<sup>th</sup>January 2020</em></p>
                  <p>WHO had set up the IMST (Incident Management Support Team) across the three levels of the organization: headquarters, regional headquarters and country level, putting the organization on an emergency footing for dealing with the outbreak.</p>
                </li>
                <li>
                  <p><em>4<sup>th</sup>January 2020</em></p>
                  <p>WHO reported on social media that there was a cluster of pneumonia cases – with no deaths – in Wuhan, Hubei province.</p>
                </li>
                <li>
                  <p><em>5<sup>th</sup>January 2020</em></p>
                  <p>WHO published our first Disease Outbreak News on the new virus. This is a flagship technical publication to the scientific and public health community as well as global media. It contained a risk assessment and advice, and reported on what China had told the organization about the status of patients and the public health response on the cluster of pneumonia cases in Wuhan.</p>
                </li>
                <li>
                  <p><em>10<sup>th</sup>January 2020</em></p>
                  <p>WHO issued a comprehensive package of technical guidance online with advice to all countries on how to detect, test and manage potential cases, based on what was known about the virus at the time. This guidance was shared with WHO's regional emergency directors to share with WHO representatives in countries.</p>
                  <p>Based on experience with SARS and MERS and known modes of transmission of respiratory viruses, infection and prevention control guidance were published to protect health workers recommending droplet and contact precautions when caring for patients, and airborne precautions for aerosol generating procedures conducted by health workers.</p>
                </li>
              </ul>
